add echo-messaging actor template
wasmCloud/project-templates pull request #63
Opened 2023-01-12 17:58 UTC by connorsmith256

Tested on a branch of `wash` referencing my fork: `wash new actor`, followed by `wash build`, followed by starting and linking the actor on a wasmcloud host and confirming that the actor echos requests over NATS back as a response

Signed-off-by: Connor Smith <connor@cosmonic.com>

2023-01-12 18:14 UTC, autodidaddict approved these changes

2023-01-12 18:39 UTC, brooksmtownsend requested changes

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/.cargo/config.toml
> +target = "wasm32-unknown-unknown"
Let's make this `wasm32-wasi`!

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/Cargo.toml
> +opt-level = "s"
If you want to add `strip=true` here the Wasm binary will get smaller

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/README.md
> +string containing fields from the request.
This looks like leftovers from another template,  you may want to just update this with a little info on the actor

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/actor.mk
> +# common makefile rules for building actors
We can remove the Makefile entirely now that wash build is up-to-snuff

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/actor.mk
> +# common makefile rules for building actors
Actually, since it's referenced in the actions, I'm OK with fixing this in another PR for the rest of the repo

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/src/lib.rs
> +impl MessageSubscriber for EchoMessagingActor {
This struct and impl should be `{{to_pascal_case project-name}}Actor` so it takes the name that the user supplies

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/Cargo.toml
> +name = "echo-messaging"
This name should be `{{project-name}}`

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/Cargo.toml
> +name = "echo_messaging"
This lib name should be `{{to_snake_case project-name}}`

2023-01-12 18:39 UTC, brooksmtownsend commented on actor/echo-messaging/wasmcloud.toml
> +[actor]
Regarding the first comment, just add this under the [actor] block for WASI compilation 
```
wasm_target = "wasm32-wasi"

```

2023-01-13 14:27 UTC, brooksmtownsend approved these changes

2023-01-13 18:09 UTC, merged